SEED: 1337
DATALOADER:
  NUM_WORKERS: 0
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: 2
  RESNETS:
    OUT_FEATURES: [ "res2", "res3", "res4", "res5" ]
  FPN:
    IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
  PROPOSAL_GENERATOR:
    NAME: "RPN"
    GAM_TOPK: False
  ANCHOR_GENERATOR:
    SIZES: [ [ 16 ], [ 32 ], [ 64 ], [ 128 ] ]  # One size for each in feature map
    ASPECT_RATIOS: [ [ 0.5, 1.0, 2.0 ] ]  # Three aspect ratios (same for all in feature maps)
  RPN:
    HEAD_NAME: "StandardRPNHead"
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
    IOU_THRESHOLDS: [ 0.3, 0.7 ]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 500
    POST_NMS_TOPK_TEST: 500
    NMS_THRESH: 0.5
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
    NUM_CLASSES: 1
    NMS_THRESH_TEST: 0.1
    PROPOSAL_APPEND_GT: True
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    GEOMETRIC_FEATURE: True
    NUM_RELATIONS: 32
    NUM_RM: [ 1, 1 ]
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
DATASETS:
  TRAIN: ("All_TRAIN",)
  TEST: ("All_VAL",)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.002
  STEPS: (60000, 80000)
  MAX_ITER: 90000
TEST:
  EVAL_PERIOD: 10000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
