_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "/home/sun/MyProjects/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  RPN:
    HEAD_NAME: "CASA_RPNHead"
  ROI_HEADS:
    NAME: "StandardROIHeads_RM"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead_RM"