_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "/home/sun/MyProjects/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "StandardROIHeads_RM"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead_RM"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000